import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        'bg-0': 'var(--bg-0)',
        'bg-1': 'var(--bg-1)',
        'bg-2': 'var(--bg-2)',
        'bg-3': 'var(--bg-3)',
        'bg-4': 'var(--bg-4)',
        'bg-inverse': 'var(--bg-inverse)',
        'fg-0': 'var(--fg-0)',
        'fg-1': 'var(--fg-1)',
        'fg-2': 'var(--fg-2)',
        'fg-3': 'var(--fg-3)',
        'fg-on-volt': 'var(--fg-on-volt)',
        volt: 'var(--volt)',
        'volt-hover': 'var(--volt-hover)',
        'volt-press': 'var(--volt-press)',
        'volt-soft': 'var(--volt-soft)',
        ion: 'var(--ion)',
        'ion-soft': 'var(--ion-soft)',
        ultraviolet: 'var(--ultraviolet)',
        'ultraviolet-soft': 'var(--ultraviolet-soft)',
        flux: 'var(--flux)',
        'flux-soft': 'var(--flux-soft)',
        buzz: 'var(--buzz)',
        'buzz-soft': 'var(--buzz-soft)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        'warning-soft': 'var(--warning-soft)',
        danger: 'var(--danger)',
        'danger-soft': 'var(--danger-soft)',
        info: 'var(--info)',
      },
      borderColor: {
        DEFAULT: 'var(--line)',
        line: 'var(--line)',
        'line-faint': 'var(--line-faint)',
        'line-subtle': 'var(--line-subtle)',
        'line-strong': 'var(--line-strong)',
        'line-volt': 'var(--line-volt)',
        'buzz-border': 'var(--buzz-border)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        pill: 'var(--radius-pill)',
      },
      fontFamily: {
        display: 'var(--font-display)',
        body: 'var(--font-body)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        md: 'var(--text-md)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
        '6xl': 'var(--text-6xl)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        'bloom-volt': 'var(--bloom-volt)',
        'bloom-volt-sm': 'var(--bloom-volt-sm)',
        'bloom-ion': 'var(--bloom-ion)',
        'bloom-ultraviolet': 'var(--bloom-ultraviolet)',
        'bloom-flux': 'var(--bloom-flux)',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out)',
        'in-out': 'var(--ease-in-out)',
        spring: 'var(--ease-spring)',
      },
      transitionDuration: {
        fast: '120ms',
        base: '200ms',
        slow: '360ms',
        slower: '600ms',
      },
      zIndex: {
        base: '0',
        card: '10',
        sticky: '100',
        overlay: '500',
        modal: '1000',
        toast: '2000',
      },
    },
  },
  plugins: [],
};

export default config;
